# Generated by Django 6.1.1 on 2026-09-03 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.enrollment'),
        ),
        migrations.AddField(
            model_name='mark',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.enrollment'),
        ),
        migrations.AddField(
            model_name='mark',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='academics.module'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.module'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('enrollment', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'module', 'year')},
        ),
    ]
